import './styles/globals.scss';
import CookieBanner from './CookieBanner';
import HeadBanner from './headBanner';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeadBanner />
        {children}
        <footer>
          <CookieBanner />
          <br />
          @Patrik Productions
        </footer>
      </body>
    </html>
  );
}
